# Generated by Django 2.2.7 on 2019-12-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20191204_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='_post_id',
            new_name='_post',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='name',
            new_name='author',
        ),
    ]
    atomic = False
